/* Die Vereinswelt des Karriere-Modus — erzeugt von
   data-pipeline/wikidata_career_world.mjs, nicht von Hand ändern.

   Anders als LIGA_VEREINE in leagueClubs.js trägt diese Liste KEINE Jahre: Die
   Saisons des Karriere-Modus sind abstrakt. Ein Verein steht in genau einer Liga —
   bei Auf- und Absteigern in der höheren, in der er zuletzt spielte.

   `stufe` ist die Spielklasse. Sie ist der Grund, warum es diese Datei gibt:
   Ohne zweite Ligen gäbe es keine Leihe nach unten und keinen Aufstieg. */
export const WELT_LIGEN = [
  { key: "BL", name: "Bundesliga", land: "GER", stufe: 1, plaetze: 18 },
  { key: "BL2", name: "2. Bundesliga", land: "GER", stufe: 2, plaetze: 18 },
  { key: "PL", name: "Premier League", land: "ENG", stufe: 1, plaetze: 20 },
  { key: "PL2", name: "Championship", land: "ENG", stufe: 2, plaetze: 24 },
  { key: "LL", name: "LaLiga", land: "ESP", stufe: 1, plaetze: 20 },
  { key: "LL2", name: "LaLiga 2", land: "ESP", stufe: 2, plaetze: 22 },
  { key: "SA", name: "Serie A", land: "ITA", stufe: 1, plaetze: 20 },
  { key: "SA2", name: "Serie B", land: "ITA", stufe: 2, plaetze: 20 },
  { key: "L1", name: "Ligue 1", land: "FRA", stufe: 1, plaetze: 18 },
  { key: "L2", name: "Ligue 2", land: "FRA", stufe: 2, plaetze: 18 },
  { key: "PT", name: "Primeira Liga", land: "PRT", stufe: 1, plaetze: 18 },
  { key: "PT2", name: "Liga Portugal 2", land: "PRT", stufe: 2, plaetze: 18 },
  { key: "NL", name: "Eredivisie", land: "NED", stufe: 1, plaetze: 18 },
  { key: "NL2", name: "Eerste Divisie", land: "NED", stufe: 2, plaetze: 20 },
];

export const WELT_VEREINE = [
  { key: "HEI", name: "1. FC Heidenheim", qid: "Q162251", lg: "BL" },
  { key: "KOE", name: "1. FC Köln", qid: "Q104770", lg: "BL" },
  { key: "FCU", name: "1. FC Union Berlin", qid: "Q141971", lg: "BL" },
  { key: "M05", name: "1. FSV Mainz 05", qid: "Q105254", lg: "BL" },
  { key: "B04", name: "Bayer 04 Leverkusen", qid: "Q104761", lg: "BL" },
  { key: "BVB", name: "Borussia Dortmund", qid: "Q41420", lg: "BL" },
  { key: "BMG", name: "Borussia Mönchengladbach", qid: "Q101959", lg: "BL" },
  { key: "SGE", name: "Eintracht Frankfurt", qid: "Q38245", lg: "BL" },
  { key: "AUG", name: "FC Augsburg", qid: "Q15755", lg: "BL" },
  { key: "FCB", name: "FC Bayern München", qid: "Q15789", lg: "BL" },
  { key: "S04", name: "FC Schalke 04", qid: "Q32494", lg: "BL" },
  { key: "STP", name: "FC St. Pauli", qid: "Q6463", lg: "BL" },
  { key: "HSV", name: "Hamburger SV", qid: "Q51974", lg: "BL" },
  { key: "BSC", name: "Hertha BSC", qid: "Q102720", lg: "BL" },
  { key: "KSV", name: "Holstein Kiel", qid: "Q157828", lg: "BL" },
  { key: "RBL", name: "RB Leipzig", qid: "Q702455", lg: "BL" },
  { key: "SCF", name: "SC Freiburg", qid: "Q106394", lg: "BL" },
  { key: "SVD", name: "SV Darmstadt 98", qid: "Q479351", lg: "BL" },
  { key: "TSG", name: "TSG 1899 Hoffenheim", qid: "Q22707", lg: "BL" },
  { key: "VFB", name: "VfB Stuttgart", qid: "Q4512", lg: "BL" },
  { key: "BOC", name: "VfL Bochum", qid: "Q105861", lg: "BL" },
  { key: "WOB", name: "VfL Wolfsburg", qid: "Q101859", lg: "BL" },
  { key: "SVW", name: "Werder Bremen", qid: "Q51976", lg: "BL" },
  { key: "FCK", name: "1. FC Kaiserslautern", qid: "Q8466", lg: "BL2" },
  { key: "1FCM", name: "1. FC Magdeburg", qid: "Q155730", lg: "BL2" },
  { key: "FCN", name: "1. FC Nürnberg", qid: "Q15786", lg: "BL2" },
  { key: "ALE", name: "Alemannia Aachen", qid: "Q153535", lg: "BL2" },
  { key: "DSC", name: "Arminia Bielefeld", qid: "Q105844", lg: "BL2" },
  { key: "DYN", name: "Dynamo Dresden", qid: "Q141931", lg: "BL2" },
  { key: "EBS", name: "Eintracht Braunschweig", qid: "Q154053", lg: "BL2" },
  { key: "ENE", name: "Energie Cottbus", qid: "Q107818", lg: "BL2" },
  { key: "FCE", name: "FC Erzgebirge Aue", qid: "Q97927365", lg: "BL2" },
  { key: "ING", name: "FC Ingolstadt 04", qid: "Q170117", lg: "BL2" },
  { key: "F95", name: "Fortuna Düsseldorf", qid: "Q151747", lg: "BL2" },
  { key: "FSV", name: "FSV Frankfurt", qid: "Q157352", lg: "BL2" },
  { key: "H96", name: "Hannover 96", qid: "Q33748", lg: "BL2" },
  { key: "HAK", name: "Hansa Rostock", qid: "Q142005", lg: "BL2" },
  { key: "KAR", name: "Karlsruher SC", qid: "Q105853", lg: "BL2" },
  { key: "MSV", name: "MSV Duisburg", qid: "Q154293", lg: "BL2" },
  { key: "ROT", name: "Rot-Weiß Oberhausen", qid: "Q157020", lg: "BL2" },
  { key: "PAD", name: "SC Paderborn 07", qid: "Q160532", lg: "BL2" },
  { key: "SGF", name: "SpVgg Greuther Fürth", qid: "Q153539", lg: "BL2" },
  { key: "SSG", name: "SSV Jahn Regensburg", qid: "Q265570", lg: "BL2" },
  { key: "SVS", name: "SV Sandhausen", qid: "Q639525", lg: "BL2" },
  { key: "SVN", name: "SV Wehen Wiesbaden", qid: "Q310621", lg: "BL2" },
  { key: "TSV", name: "TSV 1860 München", qid: "Q131603", lg: "BL2" },
  { key: "VFK", name: "VfL Osnabrück", qid: "Q160530", lg: "BL2" },
  { key: "VFR", name: "VfR Aalen", qid: "Q692586", lg: "BL2" },
  { key: "WUR", name: "Würzburger Kickers", qid: "Q535785", lg: "BL2" },
  { key: "AJE", name: "AJ Auxerre", qid: "Q182876", lg: "L1" },
  { key: "ASM", name: "AS Monaco", qid: "Q180305", lg: "L1" },
  { key: "EST", name: "ES Troyes AC", qid: "Q501693", lg: "L1" },
  { key: "FCLO", name: "FC Lorient", qid: "Q48911", lg: "L1" },
  { key: "FCTO", name: "FC Toulouse", qid: "Q19518", lg: "L1" },
  { key: "LEH", name: "Le Havre AC", qid: "Q328658", lg: "L1" },
  { key: "LEM", name: "Le Mans FC", qid: "Q210864", lg: "L1" },
  { key: "OGC", name: "OGC Nizza", qid: "Q185163", lg: "L1" },
  { key: "OL", name: "Olympique Lyon", qid: "Q704", lg: "L1" },
  { key: "OM", name: "Olympique Marseille", qid: "Q132885", lg: "L1" },
  { key: "LIL", name: "OSC Lille", qid: "Q19516", lg: "L1" },
  { key: "PAC", name: "Paris FC", qid: "Q1051013", lg: "L1" },
  { key: "PSG", name: "Paris Saint-Germain", qid: "Q483020", lg: "L1" },
  { key: "RAG", name: "Racing Straßburg", qid: "Q126334", lg: "L1" },
  { key: "RCL", name: "RC Lens", qid: "Q191843", lg: "L1" },
  { key: "SCO", name: "SCO Angers", qid: "Q845137", lg: "L1" },
  { key: "STA", name: "Stade Brest", qid: "Q218372", lg: "L1" },
  { key: "STAD", name: "Stade Rennes", qid: "Q19509", lg: "L1" },
  { key: "ACA", name: "AC Ajaccio", qid: "Q270051", lg: "L2" },
  { key: "ACN", name: "AC Arles-Avignon", qid: "Q222837", lg: "L2" },
  { key: "AFR", name: "AF Rodez", qid: "Q292231", lg: "L2" },
  { key: "ASN", name: "AS Nancy", qid: "Q19523", lg: "L2" },
  { key: "ASS", name: "AS Saint-Étienne", qid: "Q19521", lg: "L2" },
  { key: "AVE", name: "Avenir Sportif Béziers", qid: "Q2619514", lg: "L2" },
  { key: "CAB", name: "CA Bastia", qid: "Q670795", lg: "L2" },
  { key: "CHT", name: "Chamois Niort", qid: "Q626917", lg: "L2" },
  { key: "CLE", name: "Clermont Foot 63", qid: "Q870182", lg: "L2" },
  { key: "CSS", name: "CS Sedan", qid: "Q608988", lg: "L2" },
  { key: "EAG", name: "EA Guingamp", qid: "Q459148", lg: "L2" },
  { key: "FC2", name: "F.C. Annecy", qid: "Q1140695", lg: "L2" },
  { key: "FC3", name: "FC Bourg-Péronnas", qid: "Q74030", lg: "L2" },
  { key: "FCCH", name: "FC Chambly", qid: "Q3076567", lg: "L2" },
  { key: "FCEV", name: "FC Évian Thonon Gaillard", qid: "Q333838", lg: "L2" },
  { key: "FCIS", name: "FC Istres", qid: "Q797530", lg: "L2" },
  { key: "FC4", name: "FC Martigues", qid: "Q1132418", lg: "L2" },
  { key: "FCZ", name: "FC Metz", qid: "Q221525", lg: "L2" },
  { key: "FCNA", name: "FC Nantes", qid: "Q192071", lg: "L2" },
  { key: "FCX", name: "FC Sochaux", qid: "Q19512", lg: "L2" },
  { key: "FC6", name: "FC Tours", qid: "Q822021", lg: "L2" },
  { key: "FCVA", name: "FC Valenciennes", qid: "Q212269", lg: "L2" },
  { key: "FCOD", name: "FCO Dijon", qid: "Q503317", lg: "L2" },
  { key: "GFC", name: "GFC Ajaccio", qid: "Q627334", lg: "L2" },
  { key: "GI1", name: "Girondins Bordeaux", qid: "Q172476", lg: "L2" },
  { key: "GRE", name: "Grenoble Foot", qid: "Q209509", lg: "L2" },
  { key: "HSC", name: "HSC Montpellier", qid: "Q19513", lg: "L2" },
  { key: "LBC", name: "LB Châteauroux", qid: "Q845067", lg: "L2" },
  { key: "OCV", name: "OC Vannes", qid: "Q870173", lg: "L2" },
  { key: "OLY", name: "Olympique Nîmes", qid: "Q730809", lg: "L2" },
  { key: "PAU", name: "Pau Football Club", qid: "Q288419", lg: "L2" },
  { key: "RES", name: "Red Star Paris", qid: "Q522283", lg: "L2" },
  { key: "SCA", name: "SC Amiens", qid: "Q866884", lg: "L2" },
  { key: "SCB", name: "SC Bastia", qid: "Q208399", lg: "L2" },
  { key: "SMC", name: "SM Caen", qid: "Q193377", lg: "L2" },
  { key: "STL", name: "Stade Laval", qid: "Q760736", lg: "L2" },
  { key: "STS", name: "Stade Reims", qid: "Q208228", lg: "L2" },
  { key: "USB", name: "US Boulogne", qid: "Q309400", lg: "L2" },
  { key: "USCR", name: "US Créteil", qid: "Q492159", lg: "L2" },
  { key: "USO", name: "US Orléans", qid: "Q369349", lg: "L2" },
  { key: "USQ", name: "US Quevilly", qid: "Q1465560", lg: "L2" },
  { key: "USLD", name: "USL Dunkerque", qid: "Q1815297", lg: "L2" },
  { key: "ATH", name: "Athletic Bilbao", qid: "Q8687", lg: "LL" },
  { key: "ATM", name: "Atlético Madrid", qid: "Q8701", lg: "LL" },
  { key: "BET", name: "Betis Sevilla", qid: "Q8723", lg: "LL" },
  { key: "OSA", name: "CA Osasuna", qid: "Q10286", lg: "LL" },
  { key: "CEL", name: "Celta Vigo", qid: "Q8749", lg: "LL" },
  { key: "DEP", name: "Deportivo A Coruña", qid: "Q8760", lg: "LL" },
  { key: "ALA", name: "Deportivo Alavés", qid: "Q223620", lg: "LL" },
  { key: "ESP", name: "Espanyol Barcelona", qid: "Q8780", lg: "LL" },
  { key: "BAR", name: "FC Barcelona", qid: "Q7156", lg: "LL" },
  { key: "ELC", name: "FC Elche", qid: "Q10512", lg: "LL" },
  { key: "GET", name: "FC Getafe", qid: "Q8806", lg: "LL" },
  { key: "MLG", name: "FC Málaga", qid: "Q8857", lg: "LL" },
  { key: "SEV", name: "FC Sevilla", qid: "Q10329", lg: "LL" },
  { key: "VAL", name: "FC Valencia", qid: "Q10333", lg: "LL" },
  { key: "VIL", name: "FC Villarreal", qid: "Q12297", lg: "LL" },
  { key: "HER", name: "Hércules Alicante", qid: "Q11963", lg: "LL" },
  { key: "LEV", name: "Levante UD", qid: "Q8823", lg: "LL" },
  { key: "RAC", name: "Racing de Santander", qid: "Q12236", lg: "LL" },
  { key: "RAY", name: "Rayo Vallecano", qid: "Q10300", lg: "LL" },
  { key: "RMA", name: "Real Madrid", qid: "Q8682", lg: "LL" },
  { key: "RSO", name: "Real Sociedad", qid: "Q10315", lg: "LL" },
  { key: "ADA", name: "AD Alcorcón", qid: "Q10383", lg: "LL2" },
  { key: "ALB", name: "Albacete Balompié", qid: "Q576285", lg: "LL2" },
  { key: "CDC", name: "CD Castellón", qid: "Q743557", lg: "LL2" },
  { key: "CDE", name: "CD Eldense", qid: "Q600232", lg: "LL2" },
  { key: "LEG", name: "CD Leganés", qid: "Q856119", lg: "LL2" },
  { key: "CDO", name: "CD Lugo", qid: "Q11984", lg: "LL2" },
  { key: "CDM", name: "CD Mirandés", qid: "Q11997", lg: "LL2" },
  { key: "CDN", name: "CD Numancia", qid: "Q12158", lg: "LL2" },
  { key: "CDT", name: "CD Teneriffa", qid: "Q216661", lg: "LL2" },
  { key: "EXT", name: "Extremadura UD", qid: "Q994224", lg: "LL2" },
  { key: "FCAN", name: "FC Andorra", qid: "Q1386854", lg: "LL2" },
  { key: "FCBU", name: "FC Burgos", qid: "Q852079", lg: "LL2" },
  { key: "CAD", name: "FC Cádiz", qid: "Q460448", lg: "LL2" },
  { key: "FCCA", name: "FC Cartagena", qid: "Q611653", lg: "LL2" },
  { key: "COR", name: "FC Córdoba", qid: "Q10499", lg: "LL2" },
  { key: "GIR", name: "FC Girona", qid: "Q11945", lg: "LL2" },
  { key: "GRA", name: "FC Granada", qid: "Q8812", lg: "LL2" },
  { key: "FCRE", name: "FC Reus", qid: "Q1387573", lg: "LL2" },
  { key: "GIM", name: "Gimnàstic de Tarragona", qid: "Q257984", lg: "LL2" },
  { key: "LOR", name: "Lorca FC", qid: "Q6463150", lg: "LL2" },
  { key: "RAL", name: "Racing de Ferrol", qid: "Q843396", lg: "LL2" },
  { key: "MAL", name: "RCD Mallorca", qid: "Q8835", lg: "LL2" },
  { key: "OVI", name: "Real Oviedo", qid: "Q271574", lg: "LL2" },
  { key: "ZAR", name: "Real Saragossa", qid: "Q10308", lg: "LL2" },
  { key: "VLL", name: "Real Valladolid", qid: "Q10319", lg: "LL2" },
  { key: "EIB", name: "SD Eibar", qid: "Q770740", lg: "LL2" },
  { key: "HUE", name: "SD Huesca", qid: "Q11971", lg: "LL2" },
  { key: "SDP", name: "SD Ponferradina", qid: "Q12168", lg: "LL2" },
  { key: "SEO", name: "Sevilla Atlético", qid: "Q950835", lg: "LL2" },
  { key: "SPG", name: "Sporting Gijón", qid: "Q12278", lg: "LL2" },
  { key: "ALM", name: "UD Almería", qid: "Q10407", lg: "LL2" },
  { key: "LPA", name: "UD Las Palmas", qid: "Q11979", lg: "LL2" },
  { key: "ADO", name: "ADO Den Haag", qid: "Q24904", lg: "NL" },
  { key: "AJA", name: "Ajax Amsterdam", qid: "Q81888", lg: "NL" },
  { key: "AZA", name: "AZ Alkmaar", qid: "Q191264", lg: "NL" },
  { key: "EXC", name: "Excelsior Rotterdam", qid: "Q370712", lg: "NL" },
  { key: "FC8", name: "FC Groningen", qid: "Q24711", lg: "NL" },
  { key: "FCTW", name: "FC Twente Enschede", qid: "Q19603", lg: "NL" },
  { key: "FC1", name: "FC Utrecht", qid: "Q24680", lg: "NL" },
  { key: "FCVO", name: "FC Volendam", qid: "Q738060", lg: "NL" },
  { key: "FEY", name: "Feyenoord Rotterdam", qid: "Q134241", lg: "NL" },
  { key: "FOD", name: "Fortuna Sittard", qid: "Q854167", lg: "NL" },
  { key: "GOA", name: "Go Ahead Eagles", qid: "Q749589", lg: "NL" },
  { key: "NEC", name: "NEC Nijmegen", qid: "Q318348", lg: "NL" },
  { key: "PEC", name: "PEC Zwolle", qid: "Q269151", lg: "NL" },
  { key: "PSV", name: "PSV Eindhoven", qid: "Q11938", lg: "NL" },
  { key: "SCR", name: "SC Cambuur", qid: "Q875120", lg: "NL" },
  { key: "SCH", name: "SC Heerenveen", qid: "Q200321", lg: "NL" },
  { key: "SPM", name: "Sparta Rotterdam", qid: "Q209895", lg: "NL" },
  { key: "TEL", name: "Telstar", qid: "Q1071713", lg: "NL" },
  { key: "WIL", name: "Willem II Tilburg", qid: "Q332664", lg: "NL" },
  { key: "AL1", name: "Almere City", qid: "Q653119", lg: "NL2" },
  { key: "BVD", name: "BV De Graafschap", qid: "Q221927", lg: "NL2" },
  { key: "FCH", name: "FC Den Bosch", qid: "Q875169", lg: "NL2" },
  { key: "FCDO", name: "FC Dordrecht", qid: "Q1045811", lg: "NL2" },
  { key: "FCEI", name: "FC Eindhoven", qid: "Q876699", lg: "NL2" },
  { key: "FC7", name: "FC Emmen", qid: "Q1061627", lg: "NL2" },
  { key: "FCOS", name: "FC Oss", qid: "Q1149034", lg: "NL2" },
  { key: "HET", name: "Helmond Sport", qid: "Q636315", lg: "NL2" },
  { key: "HEO", name: "Heracles Almelo", qid: "Q11961", lg: "NL2" },
  { key: "MVV", name: "MVV Maastricht", qid: "Q876568", lg: "NL2" },
  { key: "NAA", name: "NAC Breda", qid: "Q332642", lg: "NL2" },
  { key: "RKC", name: "RKC Waalwijk", qid: "Q24699", lg: "NL2" },
  { key: "ROE", name: "Roda JC Kerkrade", qid: "Q24719", lg: "NL2" },
  { key: "VIM", name: "Vitesse Arnheim", qid: "Q219233", lg: "NL2" },
  { key: "VVV", name: "VVV-Venlo", qid: "Q24689", lg: "NL2" },
  { key: "BOU", name: "AFC Bournemouth", qid: "Q19568", lg: "PL" },
  { key: "AVL", name: "Aston Villa", qid: "Q18711", lg: "PL" },
  { key: "BHA", name: "Brighton & Hove Albion", qid: "Q19453", lg: "PL" },
  { key: "CP", name: "Crystal Palace", qid: "Q19467", lg: "PL" },
  { key: "ARS", name: "FC Arsenal", qid: "Q9617", lg: "PL" },
  { key: "BLA", name: "FC Blackpool", qid: "Q19449", lg: "PL" },
  { key: "BRE", name: "FC Brentford", qid: "Q19571", lg: "PL" },
  { key: "CHE", name: "FC Chelsea", qid: "Q9616", lg: "PL" },
  { key: "EVE", name: "FC Everton", qid: "Q5794", lg: "PL" },
  { key: "FUL", name: "FC Fulham", qid: "Q18708", lg: "PL" },
  { key: "LIV", name: "FC Liverpool", qid: "Q1130849", lg: "PL" },
  { key: "IPS", name: "Ipswich Town", qid: "Q9653", lg: "PL" },
  { key: "LEE", name: "Leeds United", qid: "Q1128631", lg: "PL" },
  { key: "LEI", name: "Leicester City", qid: "Q19481", lg: "PL" },
  { key: "LUT", name: "Luton Town", qid: "Q18520", lg: "PL" },
  { key: "MCI", name: "Manchester City", qid: "Q50602", lg: "PL" },
  { key: "MUN", name: "Manchester United", qid: "Q18656", lg: "PL" },
  { key: "NEW", name: "Newcastle United", qid: "Q18716", lg: "PL" },
  { key: "NFO", name: "Nottingham Forest", qid: "Q19490", lg: "PL" },
  { key: "TOT", name: "Tottenham Hotspur", qid: "Q18741", lg: "PL" },
  { key: "SUN", name: "AFC Sunderland", qid: "Q18739", lg: "PL2" },
  { key: "AFM", name: "AFC Wrexham", qid: "Q18529", lg: "PL2" },
  { key: "BIR", name: "Birmingham City", qid: "Q19444", lg: "PL2" },
  { key: "BLB", name: "Blackburn Rovers", qid: "Q19446", lg: "PL2" },
  { key: "BOL", name: "Bolton Wanderers", qid: "Q19451", lg: "PL2" },
  { key: "BRY", name: "Bristol City", qid: "Q19456", lg: "PL2" },
  { key: "BU1", name: "Burton Albion", qid: "Q48929", lg: "PL2" },
  { key: "CAR", name: "Cardiff City", qid: "Q18662", lg: "PL2" },
  { key: "CHA", name: "Charlton Athletic", qid: "Q19462", lg: "PL2" },
  { key: "DER", name: "Derby County", qid: "Q19470", lg: "PL2" },
  { key: "FCBA", name: "FC Barnsley", qid: "Q19442", lg: "PL2" },
  { key: "BUR", name: "FC Burnley", qid: "Q19458", lg: "PL2" },
  { key: "MID", name: "FC Middlesbrough", qid: "Q18661", lg: "PL2" },
  { key: "FCMI", name: "FC Millwall", qid: "Q19487", lg: "PL2" },
  { key: "FCP", name: "FC Portsmouth", qid: "Q19604", lg: "PL2" },
  { key: "REA", name: "FC Reading", qid: "Q18729", lg: "PL2" },
  { key: "SOU", name: "FC Southampton", qid: "Q18732", lg: "PL2" },
  { key: "WAT", name: "FC Watford", qid: "Q2714", lg: "PL2" },
  { key: "HUD", name: "Huddersfield Town", qid: "Q19473", lg: "PL2" },
  { key: "HUL", name: "Hull City", qid: "Q19477", lg: "PL2" },
  { key: "LIN", name: "Lincoln City", qid: "Q18519", lg: "PL2" },
  { key: "NOR", name: "Norwich City", qid: "Q18721", lg: "PL2" },
  { key: "PRE", name: "Preston North End", qid: "Q19612", lg: "PL2" },
  { key: "QPR", name: "Queens Park Rangers", qid: "Q18723", lg: "PL2" },
  { key: "ROD", name: "Rotherham United", qid: "Q48950", lg: "PL2" },
  { key: "SHU", name: "Sheffield United", qid: "Q19607", lg: "PL2" },
  { key: "SHY", name: "Sheffield Wednesday", qid: "Q19498", lg: "PL2" },
  { key: "STK", name: "Stoke City", qid: "Q18736", lg: "PL2" },
  { key: "SWA", name: "Swansea City", qid: "Q18659", lg: "PL2" },
  { key: "WBA", name: "West Bromwich Albion", qid: "Q18744", lg: "PL2" },
  { key: "WHU", name: "West Ham United", qid: "Q18747", lg: "PL2" },
  { key: "WIG", name: "Wigan Athletic", qid: "Q18750", lg: "PL2" },
  { key: "WOL", name: "Wolverhampton Wanderers", qid: "Q19500", lg: "PL2" },
  { key: "SLB", name: "Benfica Lissabon", qid: "Q131499", lg: "PT" },
  { key: "BOA", name: "Boavista Porto", qid: "Q219703", lg: "PT" },
  { key: "CAS", name: "Casa Pia AC", qid: "Q1046440", lg: "PT" },
  { key: "CDS", name: "CD Santa Clara", qid: "Q740637", lg: "PT" },
  { key: "CDA", name: "CD Tondela", qid: "Q1023227", lg: "PT" },
  { key: "DESP", name: "Desportivo Aves", qid: "Q1023163", lg: "PT" },
  { key: "FCAR", name: "FC Arouca", qid: "Q1386869", lg: "PT" },
  { key: "FCFA", name: "FC Famalicão", qid: "Q1387105", lg: "PT" },
  { key: "FCPE", name: "FC Penafiel", qid: "Q1387471", lg: "PT" },
  { key: "POR", name: "FC Porto", qid: "Q128446", lg: "PT" },
  { key: "GDE", name: "GD Estoril Praia", qid: "Q634829", lg: "PT" },
  { key: "GIL", name: "Gil Vicente FC", qid: "Q926438", lg: "PT" },
  { key: "MAR", name: "Marítimo Funchal", qid: "Q216503", lg: "PT" },
  { key: "MOR", name: "Moreirense FC", qid: "Q1346314", lg: "PT" },
  { key: "NAC", name: "Nacional Funchal", qid: "Q216459", lg: "PT" },
  { key: "RIO", name: "Rio Ave FC", qid: "Q622432", lg: "PT" },
  { key: "SPOR", name: "Sporting Braga", qid: "Q75684", lg: "PT" },
  { key: "SCP", name: "Sporting Lissabon", qid: "Q75729", lg: "PT" },
  { key: "VIT", name: "Vitória Guimarães", qid: "Q223450", lg: "PT" },
  { key: "VITO", name: "Vitória Setúbal", qid: "Q208585", lg: "PT" },
  { key: "ACAD", name: "Académica de Coimbra", qid: "Q243235", lg: "PT2" },
  { key: "AC1", name: "Académico de Viseu FC", qid: "Q2410944", lg: "PT2" },
  { key: "BEL", name: "Belenenses Lissabon", qid: "Q216510", lg: "PT2" },
  { key: "CDCO", name: "CD Cova da Piedade", qid: "Q17524289", lg: "PT2" },
  { key: "CDF", name: "CD Feirense", qid: "Q671042", lg: "PT2" },
  { key: "CDTR", name: "CD Trofense", qid: "Q1023233", lg: "PT2" },
  { key: "FCPA", name: "FC Paços de Ferreira", qid: "Q371136", lg: "PT2" },
  { key: "FCVI", name: "FC Vizela", qid: "Q1387855", lg: "PT2" },
  { key: "GDC", name: "GD Chaves", qid: "Q543467", lg: "PT2" },
  { key: "LEC", name: "Leixões SC", qid: "Q623730", lg: "PT2" },
  { key: "POC", name: "Portimonense SC", qid: "Q621120", lg: "PT2" },
  { key: "REZ", name: "Real SC Queluz", qid: "Q3106966", lg: "PT2" },
  { key: "SCC", name: "SC Covilhã", qid: "Q1891367", lg: "PT2" },
  { key: "SCE", name: "SC Farense", qid: "Q744353", lg: "PT2" },
  { key: "SCFR", name: "SC Freamunde", qid: "Q1031307", lg: "PT2" },
  { key: "SCU", name: "SC União Torreense", qid: "Q1853273", lg: "PT2" },
  { key: "UDO", name: "UD Oliveirense", qid: "Q2061414", lg: "PT2" },
  { key: "UNI", name: "União Leiria", qid: "Q211401", lg: "PT2" },
  { key: "UNA", name: "União Madeira", qid: "Q1762119", lg: "PT2" },
  { key: "VAC", name: "Varzim SC", qid: "Q1429473", lg: "PT2" },
  { key: "ACF", name: "AC Florenz", qid: "Q2052", lg: "SA" },
  { key: "MIL", name: "AC Milan", qid: "Q1543", lg: "SA" },
  { key: "ACM", name: "AC Monza", qid: "Q289482", lg: "SA" },
  { key: "ROM", name: "AS Rom", qid: "Q2739", lg: "SA" },
  { key: "ATA", name: "Atalanta Bergamo", qid: "Q1886", lg: "SA" },
  { key: "CAG", name: "Cagliari Calcio", qid: "Q1900", lg: "SA" },
  { key: "CFC", name: "CFC Genua", qid: "Q2074", lg: "SA" },
  { key: "COM", name: "Como 1907", qid: "Q1120838", lg: "SA" },
  { key: "FCBO", name: "FC Bologna", qid: "Q1893", lg: "SA" },
  { key: "FCT", name: "FC Turin", qid: "Q2768", lg: "SA" },
  { key: "FCV", name: "FC Venedig", qid: "Q501245", lg: "SA" },
  { key: "FRO", name: "Frosinone Calcio", qid: "Q845043", lg: "SA" },
  { key: "INT", name: "Inter Mailand", qid: "Q631", lg: "SA" },
  { key: "JUV", name: "Juventus Turin", qid: "Q1422", lg: "SA" },
  { key: "LAZ", name: "Lazio Rom", qid: "Q2609", lg: "SA" },
  { key: "PAR", name: "Parma Calcio 1913", qid: "Q2693", lg: "SA" },
  { key: "NAP", name: "SSC Neapel", qid: "Q2641", lg: "SA" },
  { key: "USL", name: "U.S. Lecce", qid: "Q13391", lg: "SA" },
  { key: "UDI", name: "Udinese Calcio", qid: "Q2798", lg: "SA" },
  { key: "USS", name: "US Sassuolo Calcio", qid: "Q8603", lg: "SA" },
  { key: "ACC", name: "AC Cesena", qid: "Q6664", lg: "SA2" },
  { key: "ACP", name: "AC Perugia Calcio", qid: "Q16344", lg: "SA2" },
  { key: "ACR", name: "ACR Siena 1904", qid: "Q2756", lg: "SA2" },
  { key: "ASA", name: "AS Avellino 1912", qid: "Q298217", lg: "SA2" },
  { key: "ASC", name: "AS Cittadella", qid: "Q6673", lg: "SA2" },
  { key: "ASG", name: "AS Gubbio 1910", qid: "Q298314", lg: "SA2" },
  { key: "ASO", name: "Ascoli Calcio", qid: "Q6630", lg: "SA2" },
  { key: "ASGN", name: "ASG Nocerina", qid: "Q297680", lg: "SA2" },
  { key: "BEN", name: "Benevento Calcio", qid: "Q652516", lg: "SA2" },
  { key: "BR1", name: "Brescia Calcio", qid: "Q6651", lg: "SA2" },
  { key: "CAL", name: "Calcio Foggia 1920", qid: "Q139399", lg: "SA2" },
  { key: "CAA", name: "Calcio Padova", qid: "Q8428", lg: "SA2" },
  { key: "CALC", name: "Calcio Portogruaro Summaga", qid: "Q913041", lg: "SA2" },
  { key: "CARR", name: "Carrarese Calcio", qid: "Q650365", lg: "SA2" },
  { key: "CAT", name: "Catania FC", qid: "Q2018", lg: "SA2" },
  { key: "CHI", name: "Chievo Verona", qid: "Q2037", lg: "SA2" },
  { key: "COS", name: "Cosenza Calcio 1914", qid: "Q1136016", lg: "SA2" },
  { key: "DEL", name: "Delfino Pescara 1936", qid: "Q2710", lg: "SA2" },
  { key: "FC5", name: "F.C. Trapani 1905", qid: "Q2114224", lg: "SA2" },
  { key: "FC9", name: "FC Carpi", qid: "Q610621", lg: "SA2" },
  { key: "FCCR", name: "FC Crotone", qid: "Q6690", lg: "SA2" },
  { key: "FCEM", name: "FC Empoli", qid: "Q6703", lg: "SA2" },
  { key: "FCMO", name: "FC Modena", qid: "Q8408", lg: "SA2" },
  { key: "FCO", name: "FC Palermo", qid: "Q2674", lg: "SA2" },
  { key: "FCPR", name: "FC Pro Vercelli", qid: "Q8455", lg: "SA2" },
  { key: "HEL", name: "Hellas Verona", qid: "Q8639", lg: "SA2" },
  { key: "JUA", name: "Juve Stabia", qid: "Q6748", lg: "SA2" },
  { key: "LRV", name: "L.R. Vicenza", qid: "Q56542463", lg: "SA2" },
  { key: "LAN", name: "Lanciano Calcio 1920", qid: "Q8648", lg: "SA2" },
  { key: "LAT", name: "Latina Calcio 1932", qid: "Q2118510", lg: "SA2" },
  { key: "MAN", name: "Mantova 1911", qid: "Q430993", lg: "SA2" },
  { key: "NOV", name: "Novara Calcio", qid: "Q8416", lg: "SA2" },
  { key: "PIA", name: "Piacenza Calcio 1919", qid: "Q459794", lg: "SA2" },
  { key: "PIS", name: "Pisa SC", qid: "Q289613", lg: "SA2" },
  { key: "POO", name: "Pordenone Calcio", qid: "Q257078", lg: "SA2" },
  { key: "REG", name: "Reggina 1914", qid: "Q8476", lg: "SA2" },
  { key: "SAM", name: "Sampdoria Genua", qid: "Q1457", lg: "SA2" },
  { key: "SPA", name: "SPAL Ferrara", qid: "Q13385", lg: "SA2" },
  { key: "SPE", name: "Spezia Calcio", qid: "Q8615", lg: "SA2" },
  { key: "SSA", name: "SS Arezzo", qid: "Q297430", lg: "SA2" },
  { key: "SSC", name: "SSC Bari", qid: "Q6641", lg: "SA2" },
  { key: "TER", name: "Ternana Calcio", qid: "Q8623", lg: "SA2" },
  { key: "US9", name: "U.S. Salernitana 1919", qid: "Q847587", lg: "SA2" },
  { key: "UST", name: "U.S. Triestina Calcio 1918", qid: "Q13381", lg: "SA2" },
  { key: "UCA", name: "UC AlbinoLeffe", qid: "Q752483", lg: "SA2" },
  { key: "USC", name: "US Catanzaro", qid: "Q501372", lg: "SA2" },
  { key: "USE", name: "US Cremonese", qid: "Q759482", lg: "SA2" },
  { key: "USG", name: "US Grosseto", qid: "Q6721", lg: "SA2" },
  { key: "US5", name: "US Livorno 1915", qid: "Q6767", lg: "SA2" },
  { key: "VAR", name: "Varese Calcio", qid: "Q8633", lg: "SA2" },
  { key: "VIC", name: "Vicenza Calcio", qid: "Q8643", lg: "SA2" },
  { key: "VIR", name: "Virtus Entella", qid: "Q2276413", lg: "SA2" },
];
