/* ──────────────────────────────────────────────────────────────────────────
   POSSESSION PLAY — Spielerdaten (entkoppelt von der Spiel-Logik)

   Datenformat pro Spieler:
     { n: "Voller Name", ln: "Nachname (Suchschlüssel)", by: Geburtsjahr,
       nat: ["ISO3", ...], clubs: ["VEREINS-KEY", ...] }

   Aktuell: kuratierter DEMO-Seed (~108 bekannte Spieler).

   Volldatensatz einsetzen: den Inhalt der per Kaggle erzeugten
   players_game.js (aus data-pipeline/) hier hineinkopieren und damit das
   gesamte Array unten ersetzen — das "export const PLAYERS = [" davor
   stehen lassen. Anleitung: data-pipeline/README.md
   ────────────────────────────────────────────────────────────────────────── */

export const PLAYERS = [
  { n: "Lionel Messi", ln: "Messi", by: 1987, nat: ["ARG"], clubs: ["BAR", "PSG"] },
  { n: "Cristiano Ronaldo", ln: "Ronaldo", by: 1985, nat: ["PRT"], clubs: ["SCP", "MUN", "RMA", "JUV"] },
  { n: "Kylian Mbappé", ln: "Mbappé", by: 1998, nat: ["FRA"], clubs: ["ASM", "PSG", "RMA"] },
  { n: "Erling Haaland", ln: "Haaland", by: 2000, nat: [], clubs: ["BVB", "MCI"] },
  { n: "Jude Bellingham", ln: "Bellingham", by: 2003, nat: ["ENG"], clubs: ["BVB", "RMA"] },
  { n: "Vinícius Júnior", ln: "Vinícius Júnior", by: 2000, nat: ["BRA"], clubs: ["RMA"] },
  { n: "Vitinha", ln: "Vitinha", by: 2000, nat: ["PRT"], clubs: ["POR", "PSG"] },
  { n: "Pedri", ln: "Pedri", by: 2002, nat: ["ESP"], clubs: ["BAR"] },
  { n: "Gavi", ln: "Gavi", by: 2004, nat: ["ESP"], clubs: ["BAR"] },
  { n: "Lamine Yamal", ln: "Yamal", by: 2007, nat: ["ESP"], clubs: ["BAR"] },
  { n: "Robert Lewandowski", ln: "Lewandowski", by: 1988, nat: [], clubs: ["BVB", "FCB", "BAR"] },
  { n: "Toni Kroos", ln: "Kroos", by: 1990, nat: ["GER"], clubs: ["FCB", "B04", "RMA"] },
  { n: "Thomas Müller", ln: "Müller", by: 1989, nat: ["GER"], clubs: ["FCB"] },
  { n: "Manuel Neuer", ln: "Neuer", by: 1986, nat: ["GER"], clubs: ["FCB"] },
  { n: "Joshua Kimmich", ln: "Kimmich", by: 1995, nat: ["GER"], clubs: ["RBL", "FCB"] },
  { n: "Leon Goretzka", ln: "Goretzka", by: 1995, nat: ["GER"], clubs: ["FCB"] },
  { n: "Jamal Musiala", ln: "Musiala", by: 2003, nat: ["GER"], clubs: ["FCB"] },
  { n: "Florian Wirtz", ln: "Wirtz", by: 2003, nat: ["GER"], clubs: ["B04", "LIV"] },
  { n: "Kai Havertz", ln: "Havertz", by: 1999, nat: ["GER"], clubs: ["B04", "CHE", "ARS"] },
  { n: "Leroy Sané", ln: "Sané", by: 1996, nat: ["GER"], clubs: ["MCI", "FCB"] },
  { n: "Serge Gnabry", ln: "Gnabry", by: 1995, nat: ["GER"], clubs: ["ARS", "SVW", "FCB"] },
  { n: "İlkay Gündoğan", ln: "Gündoğan", by: 1990, nat: ["GER"], clubs: ["BVB", "MCI", "BAR"] },
  { n: "Antonio Rüdiger", ln: "Rüdiger", by: 1993, nat: ["GER"], clubs: ["VFB", "ROM", "CHE", "RMA"] },
  { n: "Mats Hummels", ln: "Hummels", by: 1988, nat: ["GER"], clubs: ["FCB", "BVB", "ROM"] },
  { n: "Mesut Özil", ln: "Özil", by: 1988, nat: ["GER"], clubs: ["SVW", "RMA", "ARS"] },
  { n: "Philipp Lahm", ln: "Lahm", by: 1983, nat: ["GER"], clubs: ["FCB"] },
  { n: "Bastian Schweinsteiger", ln: "Schweinsteiger", by: 1984, nat: ["GER"], clubs: ["FCB", "MUN"] },
  { n: "Miroslav Klose", ln: "Klose", by: 1978, nat: ["GER"], clubs: ["SVW", "FCB", "LAZ"] },
  { n: "Marco Reus", ln: "Reus", by: 1989, nat: ["GER"], clubs: ["BMG", "BVB"] },
  { n: "Mario Götze", ln: "Götze", by: 1992, nat: ["GER"], clubs: ["BVB", "FCB", "PSV", "SGE"] },
  { n: "Kevin De Bruyne", ln: "De Bruyne", by: 1991, nat: ["BEL"], clubs: ["CHE", "WOB", "MCI"] },
  { n: "Romelu Lukaku", ln: "Lukaku", by: 1993, nat: ["BEL"], clubs: ["EVE", "MUN", "INT", "CHE", "ROM"] },
  { n: "Eden Hazard", ln: "Hazard", by: 1991, nat: ["BEL"], clubs: ["LIL", "CHE", "RMA"] },
  { n: "Thibaut Courtois", ln: "Courtois", by: 1992, nat: ["BEL"], clubs: ["ATM", "CHE", "RMA"] },
  { n: "Harry Kane", ln: "Kane", by: 1993, nat: ["ENG"], clubs: ["TOT", "FCB"] },
  { n: "Bukayo Saka", ln: "Saka", by: 2001, nat: ["ENG"], clubs: ["ARS"] },
  { n: "Phil Foden", ln: "Foden", by: 2000, nat: ["ENG"], clubs: ["MCI"] },
  { n: "Declan Rice", ln: "Rice", by: 1999, nat: ["ENG"], clubs: ["ARS"] },
  { n: "Raheem Sterling", ln: "Sterling", by: 1994, nat: ["ENG"], clubs: ["LIV", "MCI", "CHE"] },
  { n: "Marcus Rashford", ln: "Rashford", by: 1997, nat: ["ENG"], clubs: ["MUN"] },
  { n: "Jack Grealish", ln: "Grealish", by: 1995, nat: ["ENG"], clubs: ["AVL", "MCI"] },
  { n: "Trent Alexander-Arnold", ln: "Alexander-Arnold", by: 1998, nat: ["ENG"], clubs: ["LIV", "RMA"] },
  { n: "Wayne Rooney", ln: "Rooney", by: 1985, nat: ["ENG"], clubs: ["EVE", "MUN"] },
  { n: "Frank Lampard", ln: "Lampard", by: 1978, nat: ["ENG"], clubs: ["CHE", "MCI"] },
  { n: "Steven Gerrard", ln: "Gerrard", by: 1980, nat: ["ENG"], clubs: ["LIV"] },
  { n: "David Beckham", ln: "Beckham", by: 1975, nat: ["ENG"], clubs: ["MUN", "RMA", "MIL", "PSG"] },
  { n: "Mohamed Salah", ln: "Salah", by: 1992, nat: [], clubs: ["CHE", "ROM", "LIV"] },
  { n: "Sadio Mané", ln: "Mané", by: 1992, nat: ["SEN"], clubs: ["LIV", "FCB"] },
  { n: "Virgil van Dijk", ln: "van Dijk", by: 1991, nat: ["NED"], clubs: ["LIV"] },
  { n: "Luka Modrić", ln: "Modrić", by: 1985, nat: ["CRO"], clubs: ["TOT", "RMA", "MIL"] },
  { n: "Karim Benzema", ln: "Benzema", by: 1987, nat: ["FRA"], clubs: ["OL", "RMA"] },
  { n: "Antoine Griezmann", ln: "Griezmann", by: 1991, nat: ["FRA"], clubs: ["ATM", "BAR"] },
  { n: "Paul Pogba", ln: "Pogba", by: 1993, nat: ["FRA"], clubs: ["MUN", "JUV"] },
  { n: "N'Golo Kanté", ln: "Kanté", by: 1991, nat: ["FRA"], clubs: ["CHE"] },
  { n: "Olivier Giroud", ln: "Giroud", by: 1986, nat: ["FRA"], clubs: ["ARS", "CHE", "MIL"] },
  { n: "Sergio Ramos", ln: "Ramos", by: 1986, nat: ["ESP"], clubs: ["SEV", "RMA", "PSG"] },
  { n: "Gerard Piqué", ln: "Piqué", by: 1987, nat: ["ESP"], clubs: ["MUN", "BAR"] },
  { n: "Andrés Iniesta", ln: "Iniesta", by: 1984, nat: ["ESP"], clubs: ["BAR"] },
  { n: "Xavi", ln: "Xavi", by: 1980, nat: ["ESP"], clubs: ["BAR"] },
  { n: "Sergio Busquets", ln: "Busquets", by: 1988, nat: ["ESP"], clubs: ["BAR"] },
  { n: "Jordi Alba", ln: "Alba", by: 1989, nat: ["ESP"], clubs: ["VAL", "BAR"] },
  { n: "Rodri", ln: "Rodri", by: 1996, nat: ["ESP"], clubs: ["VIL", "ATM", "MCI"] },
  { n: "Neymar", ln: "Neymar", by: 1992, nat: ["BRA"], clubs: ["BAR", "PSG"] },
  { n: "Casemiro", ln: "Casemiro", by: 1992, nat: ["BRA"], clubs: ["POR", "RMA", "MUN"] },
  { n: "Thiago Silva", ln: "Silva", by: 1984, nat: ["BRA"], clubs: ["MIL", "PSG", "CHE"] },
  { n: "Marquinhos", ln: "Marquinhos", by: 1994, nat: ["BRA"], clubs: ["ROM", "PSG"] },
  { n: "Alisson", ln: "Alisson", by: 1992, nat: ["BRA"], clubs: ["ROM", "LIV"] },
  { n: "Ederson", ln: "Ederson", by: 1993, nat: ["BRA"], clubs: ["SLB", "MCI"] },
  { n: "Gabriel Jesus", ln: "Jesus", by: 1997, nat: ["BRA"], clubs: ["MCI", "ARS"] },
  { n: "Rodrygo", ln: "Rodrygo", by: 2001, nat: ["BRA"], clubs: ["RMA"] },
  { n: "Lautaro Martínez", ln: "Martínez", by: 1997, nat: ["ARG"], clubs: ["INT"] },
  { n: "Ángel Di María", ln: "Di María", by: 1988, nat: ["ARG"], clubs: ["SLB", "RMA", "MUN", "PSG", "JUV"] },
  { n: "Paulo Dybala", ln: "Dybala", by: 1993, nat: ["ARG"], clubs: ["JUV", "ROM"] },
  { n: "Gianluigi Buffon", ln: "Buffon", by: 1978, nat: ["ITA"], clubs: ["JUV", "PSG"] },
  { n: "Andrea Pirlo", ln: "Pirlo", by: 1979, nat: ["ITA"], clubs: ["INT", "MIL", "JUV"] },
  { n: "Paolo Maldini", ln: "Maldini", by: 1968, nat: ["ITA"], clubs: ["MIL"] },
  { n: "Francesco Totti", ln: "Totti", by: 1976, nat: ["ITA"], clubs: ["ROM"] },
  { n: "Alessandro Del Piero", ln: "Del Piero", by: 1974, nat: ["ITA"], clubs: ["JUV"] },
  { n: "Federico Chiesa", ln: "Chiesa", by: 1997, nat: ["ITA"], clubs: ["JUV", "LIV"] },
  { n: "Nicolò Barella", ln: "Barella", by: 1997, nat: ["ITA"], clubs: ["INT"] },
  { n: "Gianluigi Donnarumma", ln: "Donnarumma", by: 1999, nat: ["ITA"], clubs: ["MIL", "PSG", "MCI"] },
  { n: "Leonardo Bonucci", ln: "Bonucci", by: 1987, nat: ["ITA"], clubs: ["JUV", "MIL"] },
  { n: "Zlatan Ibrahimović", ln: "Ibrahimović", by: 1981, nat: [], clubs: ["AJA", "JUV", "INT", "MIL", "BAR", "PSG", "MUN"] },
  { n: "Victor Osimhen", ln: "Osimhen", by: 1998, nat: ["NGA"], clubs: ["LIL", "NAP"] },
  { n: "Khvicha Kvaratskhelia", ln: "Kvaratskhelia", by: 2001, nat: [], clubs: ["NAP", "PSG"] },
  { n: "Rafael Leão", ln: "Leão", by: 1999, nat: ["PRT"], clubs: ["SLB", "LIL", "MIL"] },
  { n: "Bruno Fernandes", ln: "Fernandes", by: 1994, nat: ["PRT"], clubs: ["SCP", "MUN"] },
  { n: "Rúben Dias", ln: "Dias", by: 1997, nat: ["PRT"], clubs: ["SLB", "MCI"] },
  { n: "Bernardo Silva", ln: "Silva", by: 1994, nat: ["PRT"], clubs: ["ASM", "MCI"] },
  { n: "João Félix", ln: "Félix", by: 1999, nat: ["PRT"], clubs: ["SLB", "ATM"] },
  { n: "Diogo Jota", ln: "Jota", by: 1996, nat: ["PRT"], clubs: ["LIV"] },
  { n: "Pepe", ln: "Pepe", by: 1983, nat: ["PRT"], clubs: ["POR", "RMA"] },
  { n: "Didier Drogba", ln: "Drogba", by: 1978, nat: ["CIV"], clubs: ["OM", "CHE"] },
  { n: "Son Heung-min", ln: "Son", by: 1992, nat: [], clubs: ["B04", "TOT"] },
  { n: "Achraf Hakimi", ln: "Hakimi", by: 1998, nat: [], clubs: ["RMA", "BVB", "INT", "PSG"] },
  { n: "Frenkie de Jong", ln: "de Jong", by: 1997, nat: ["NED"], clubs: ["AJA", "BAR"] },
  { n: "Matthijs de Ligt", ln: "de Ligt", by: 1999, nat: ["NED"], clubs: ["AJA", "JUV", "FCB", "MUN"] },
  { n: "Memphis Depay", ln: "Depay", by: 1994, nat: ["NED"], clubs: ["PSV", "MUN", "OL", "BAR", "ATM"] },
  { n: "Arjen Robben", ln: "Robben", by: 1984, nat: ["NED"], clubs: ["PSV", "CHE", "RMA", "FCB"] },
  { n: "Robin van Persie", ln: "van Persie", by: 1983, nat: ["NED"], clubs: ["FEY", "ARS", "MUN"] },
  { n: "Wesley Sneijder", ln: "Sneijder", by: 1984, nat: ["NED"], clubs: ["AJA", "RMA", "INT"] },
  { n: "Luis Suárez", ln: "Suárez", by: 1987, nat: [], clubs: ["AJA", "LIV", "BAR", "ATM"] },
  { n: "Edinson Cavani", ln: "Cavani", by: 1987, nat: [], clubs: ["NAP", "PSG", "MUN", "VAL"] },
  { n: "James Rodríguez", ln: "Rodríguez", by: 1991, nat: ["COL"], clubs: ["POR", "RMA", "FCB", "EVE"] },
  { n: "Radamel Falcao", ln: "Falcao", by: 1986, nat: ["COL"], clubs: ["POR", "ATM", "ASM", "MUN", "CHE", "OM"] },
  { n: "Christian Pulisic", ln: "Pulisic", by: 1998, nat: ["USA"], clubs: ["BVB", "CHE", "MIL"] },
  { n: "Hirving Lozano", ln: "Lozano", by: 1995, nat: ["MEX"], clubs: ["PSV", "NAP"] },
  { n: "Wataru Endo", ln: "Endo", by: 1993, nat: ["JPN"], clubs: ["VFB", "LIV"] },
];
